name: Action by Muralitharan
run-name: ${{github.actor}} is testing out Github Action
on: [push]
jobs: 
  Explore-Github-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16'
      - run: echo "Node step up succesfull"
      - run: touch index.js
      - run: echo "console.log('Hello world from Muralitharan')" >>index.js
      - run: node index.js
  Node-JS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16'
      - run: node -v
